language: ruby
rvm:
- 2.2.5
deploy:
  provider: heroku
  api_key:
    secure: pbfRxW39THX7k8cb86CHjGy4gFPjzsYd8iluDuB24UpJBHJFvlhU6MGBc1ZNj2BiwD/zbqbxm4n1v9oQXuKgT9ontup7VT9tQw3wZadegWVG5pK9HhjUJAJNaOAGVNCtwv4VrvrzDd5K54jckeCPCo9SHFITCMr39SFOAlcJMF8zMAHVXrIpvNngsIviOMWK21C5rB47GTYqIRZjMlfp2Mn8UzSYUPnPMwcCJbZJ7tEkgwMZ4E01JfCQ1FRkzdPl0DJ96JFUlDsKJxXoSWKsknBZ13bKV7hCju87/J/XaxB5MZ88P1aWDP1Jc7iAmTBekcW+dYgCkAHYCVQqkDerH/qg0noJu9OVY4oKqtDVAmc8eAj7Mubu3nJ61zbPNrRsL56YGCRoFszpRB3kIwyW6lJkeFC/GerjFwcDVCsARZn7+cPg9hBEyvswSzcB0aJJCpVlLYmJp1tjXgJTC+E/NKlQ4+XQ0YG2tu4IktdF1X3Ye0Vjsmhkm21fiy/neIgKc7sHjrA7aWWzzkY2b77Hs94amymj7BBz5L0k0yeYTT3LeQTPzZKqhOjezLyXVptpGJLcFr+AUklUxExjiWtgAWA1+q4OAEKQOkWTAVea7G4dcIhTj39inmX7F0bvyA6FX93GtLvdOQ5mqsRFJsjiRqLe1HCYAXxtNeBWNt7H1N0=
  app: damp-hollows-68891
  on:
    repo: aiit2016/rails_team_enpit
